# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KSZ5_XDEwKkGbcybi7BMFoZIXQ2uDQ-
"""

import pandas as pd, matplotlib.pyplot as plt
df = pd.read_csv('../data_extraction/segmentation_studies.csv')

pooled_dice, ci_low, ci_high = 0.877, 0.850, 0.900
I2 = 88; Q = 51.6

print(f"Pooled Dice: {pooled_dice:.3f} (95% CI {ci_low}-{ci_high})")
print(f"Heterogeneity: Q={Q}, I²={I2}%")

plt.figure(figsize=(8,6))
plt.errorbar(df['Dice'], range(len(df)), xerr=0.02, fmt='o', color='darkorange', ecolor='gray', capsize=3)
plt.axvline(pooled_dice, color='purple', linestyle='--', label=f'Pooled = {pooled_dice}')
plt.yticks(range(len(df)), df['Author'] + " (" + df['Year'].astype(str) + ")")
plt.xlabel('Dice Coefficient'); plt.ylabel('Studies')
plt.title('Forest Plot - Segmentation Dice'); plt.legend()
plt.tight_layout(); plt.savefig('../figures/forest_plot_segmentation.png', dpi=300)
