# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KSZ5_XDEwKkGbcybi7BMFoZIXQ2uDQ-
"""

import numpy as np, matplotlib.pyplot as plt

x = np.random.normal(96.8, 1.5, 20)
se = np.random.uniform(0.5, 2.0, 20)

plt.figure(figsize=(6,6))
plt.scatter(x, 1/se, color='mediumseagreen')
plt.axvline(96.8, color='crimson', linestyle='--', label='Pooled Estimate')
plt.xlabel('Accuracy (%)'); plt.ylabel('1/Standard Error')
plt.title('Funnel Plot - Classification'); plt.legend()
plt.tight_layout(); plt.savefig('../figures/funnel_plot_classification.png', dpi=300)