# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KSZ5_XDEwKkGbcybi7BMFoZIXQ2uDQ-
"""

import pandas as pd, matplotlib.pyplot as plt
from math import sqrt

# Load data
df = pd.read_csv('../data_extraction/classification_studies.csv')

# Reported pooled values
pooled_acc, ci_lower, ci_upper = 96.8, 95.5, 98.0
I2, tau2, Q = 72, 1.39, 33.1

print(f"Pooled Accuracy: {pooled_acc}% (95% CI {ci_lower}-{ci_upper})")
print(f"Heterogeneity: Q={Q}, I²={I2}%, τ²={tau2}")

# Forest plot
plt.figure(figsize=(8,6))
plt.errorbar(df['Accuracy'], range(len(df)), xerr=1.0, fmt='o', color='teal', ecolor='gray', capsize=3)
plt.axvline(pooled_acc, color='crimson', linestyle='--', label=f'Pooled = {pooled_acc}%')
plt.yticks(range(len(df)), df['Author'] + " (" + df['Year'].astype(str) + ")")
plt.xlabel('Accuracy (%)'); plt.ylabel('Studies')
plt.title('Forest Plot - Classification Accuracy')
plt.legend(); plt.tight_layout(); plt.savefig('../figures/forest_plot_classification.png', dpi=300)