# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KSZ5_XDEwKkGbcybi7BMFoZIXQ2uDQ-
"""

python scripts/meta_analysis_segmentation.py