# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KSZ5_XDEwKkGbcybi7BMFoZIXQ2uDQ-
"""

Search followed PRISMA 2020 guidelines.
Databases: PubMed, Scopus, Web of Science, IEEE Xplore, SpringerLink.
Period: 2014–2025.
Selection: 132 records → 37 included (24 classification, 15 segmentation).
Meta-analysis: Random-effects model (DerSimonian–Laird) computed pooled accuracy (96.8%) and Dice (0.877).
Heterogeneity: I²=72% (classification), 88% (segmentation). Subgroup analysis showed CNN (98.5%) and Hybrid (98.3%) performed best.
Tools: Python 3.10, Pandas, Statsmodels, Matplotlib.