# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KSZ5_XDEwKkGbcybi7BMFoZIXQ2uDQ-
"""

Author,Year,Model,XAI,Dataset,Dice,IoU,Accuracy
Sajid et al.,2019,Hybrid CNN,N/A,BraTS,0.91,0.82,--
Akil et al.,2020,Attention CNN,N/A,BraTS,0.90,0.80,--
Wang et al.,2021,ECSU-Net,N/A,SpineWeb,0.956,0.92,0.962
Guerroudji et al.,2024,AR-based 3D Framework,AR Visualization,Local,0.9861,0.96,0.986
Zhao et al.,2021,Modified GAN-cAED,Controlled Segmentation,CTA/SPET,0.94,0.91,--
Kumar et al.,2020,SPST-CNN,Spatial Pyramid Visualization,Liver,0.859,0.81,--